"""
Fully AI-driven game: dynamics model + VQ-VAE, no game engine.

This script runs a playable game where EVERYTHING is generated by neural networks:
- No physics engine
- No level generation
- No collision detection  
- Only pygame window + keyboard input + neural network inference + pixel display

Usage:
    python play_world_model.py
    python play_world_model.py --dynamics_checkpoint checkpoints/dynamics_best.pt
    python play_world_model.py --ode_steps 10 --seed_index 5
"""

import argparse
import random
import os

import pygame
import torch
import torch.nn.functional as F

from vqvae.model import VQVAE
from dynamics.model import DynamicsUNet
from dynamics.inference import predict_next_frame


class WorldModelGame:
    """Fully AI-driven game loop."""
    
    def __init__(
        self,
        vqvae_checkpoint,
        dynamics_checkpoint,
        seeds_path,
        ode_steps=10,
        seed_index=None,
        display_size=(840, 420),
        solver="euler",
        temperature=1.0,
        top_k=None,
        compile_models=True,
    ):
        """
        Args:
            vqvae_checkpoint:    path to VQ-VAE .pt file
            dynamics_checkpoint: path to dynamics model .pt file
            seeds_path:          path to seeds.pt
            ode_steps:           number of ODE integration steps
            seed_index:          which seed to use (None = random)
            display_size:        (width, height) of the pygame window
            solver:              "euler" or "midpoint"
            top_k:               top-k token sampling (None or <=0 disables)
            compile_models:      whether to compile models with torch.compile
        """
        self.ode_steps = ode_steps
        self.solver = solver
        self.temperature = temperature
        self.top_k = top_k
        self.display_size = display_size
        
        # Set up PyTorch
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"Device: {self.device}")
        torch.set_grad_enabled(False)
        
        # Load VQ-VAE
        print(f"Loading VQ-VAE from {vqvae_checkpoint}...")
        self.vqvae_model = self._load_vqvae(vqvae_checkpoint)
        
        # Load Dynamics Model
        print(f"Loading Dynamics Model from {dynamics_checkpoint}...")
        self.dynamics_model = self._load_dynamics(dynamics_checkpoint)
        
        # Compile models (optional but recommended for RTX 5070 Ti)
        if compile_models and self.device.type == "cuda":
            print("Compiling models with torch.compile (this may take a minute)...")
            try:
                # Use eager backend on Windows to avoid Triton issues
                import sys
                backend = "eager" if sys.platform == "win32" else "inductor"
                self.dynamics_model = torch.compile(self.dynamics_model, backend=backend)
                self.vqvae_decoder = torch.compile(self.vqvae_model.decoder, backend=backend)
                print(f"Models compiled successfully (backend: {backend})")
            except Exception as e:
                print(f"Warning: torch.compile failed ({e}), continuing without compilation")
                self.vqvae_decoder = self.vqvae_model.decoder
        else:
            self.vqvae_decoder = self.vqvae_model.decoder
        
        # Store VQ-VAE codebook for latent quantization during autoregressive generation
        self.codebook = self.vqvae_model.quantizer.embedding  # [K, 16]
        
        # Load seeds
        print(f"Loading seeds from {seeds_path}...")
        self.seeds = torch.load(seeds_path, map_location=self.device)['contexts']
        self.seeds = self._align_seed_contexts(self.seeds)
        self.num_seeds = self.seeds.shape[0]
        print(f"Loaded {self.num_seeds} seed sequences")
        
        # Initialize context buffer
        self.seed_index = seed_index if seed_index is not None else random.randint(0, self.num_seeds - 1)
        self.context_buffer = self.seeds[self.seed_index:self.seed_index + 1].clone()
        print(f"Using seed {self.seed_index}")
        
        # Set up Pygame
        pygame.init()
        self.screen = pygame.display.set_mode(display_size)
        pygame.display.set_caption("World Model Game - AI-Driven")
        self.clock = pygame.time.Clock()
        self.font = pygame.font.Font(None, 28)
        
        self.running = True
        self.frame_count = 0
    
    def _load_vqvae(self, checkpoint_path):
        """Load VQ-VAE model from checkpoint."""
        ckpt = torch.load(checkpoint_path, map_location=self.device, weights_only=False)
        config = ckpt.get("config", {})
        
        model = VQVAE(
            latent_dim=config.get("latent_dim", 16),
            num_embeddings=config.get("num_embeddings", 1024),
            commitment_cost=config.get("commitment_cost", 0.25),
            ema_decay=config.get("ema_decay", 0.99),
        ).to(self.device)
        
        model.load_state_dict(ckpt["model_state_dict"])
        model.eval()
        
        return model

    def _expected_context_length(self):
        """Read expected context length from raw or compiled model."""
        if hasattr(self.dynamics_model, "context_length"):
            return int(getattr(self.dynamics_model, "context_length"))
        orig_mod = getattr(self.dynamics_model, "_orig_mod", None)
        if orig_mod is not None and hasattr(orig_mod, "context_length"):
            return int(getattr(orig_mod, "context_length"))
        return None

    def _align_seed_contexts(self, contexts):
        """
        Align seed context length to what dynamics model expects.

        If too short, left-pad with the oldest frame.
        If too long, keep the most recent frames.
        """
        expected = self._expected_context_length()
        if expected is None:
            return contexts

        current = contexts.shape[1]
        if current == expected:
            return contexts
        if current > expected:
            print(f"Trimming seed context length from {current} to {expected}")
            return contexts[:, -expected:]

        pad_frames = expected - current
        print(f"Padding seed context length from {current} to {expected}")
        oldest = contexts[:, :1]
        pad = oldest.expand(-1, pad_frames, -1, -1, -1)
        return torch.cat([pad, contexts], dim=1)
    
    def _load_dynamics(self, checkpoint_path):
        """Load dynamics model from checkpoint (with EMA weights)."""
        ckpt = torch.load(checkpoint_path, map_location=self.device, weights_only=False)
        config = ckpt.get("config", {})
        context_length = config.get("context_length", 4)
        latent_dim = config.get("latent_dim", 16)
        in_channels = config.get("in_channels", latent_dim * (1 + context_length))
        
        model = DynamicsUNet(
            in_channels=in_channels,
            num_embeddings=config.get("num_embeddings", 1024),
            bottleneck_dim=config.get("bottleneck_dim", 64),
            base_channels=config.get("base_channels", 128),
            channel_mults=tuple(config.get("channel_mults", [1, 2, 2])),
            cond_dim=config.get("cond_dim", 256),
            context_length=config.get("context_length", 4),
            num_actions=config.get("num_actions", 2),
            attn_resolution=config.get("attn_resolution", 8),
        ).to(self.device)
        
        # Load EMA weights (better quality than regular weights)
        if "ema_state_dict" in ckpt:
            print("Loading EMA weights...")
            ema_weights = ckpt["ema_state_dict"]
            model_state = {}
            for name, param in model.named_parameters():
                if name in ema_weights:
                    model_state[name] = ema_weights[name]
            model.load_state_dict(model_state)
        else:
            model.load_state_dict(ckpt["model_state_dict"])
        
        model.eval()
        
        return model
    
    def _predict_next(self, action):
        """
        Run dynamics model ODE integration + codebook quantization.
        
        Returns:
            [1, 16, 32, 32] predicted next latent frame (quantized to codebook)
        """
        return predict_next_frame(
            self.dynamics_model,
            self.context_buffer,
            action,
            num_steps=self.ode_steps,
            solver=self.solver,
            device=self.device,
            codebook=self.codebook,
            temperature=self.temperature,
            top_k=self.top_k,
        )
    
    def _decode_to_pixels(self, z):
        """
        Decode latent to display-ready numpy array.
        
        Pipeline:
            z [1,16,32,32] -> VQ-VAE decoder -> [1,3,256,512] in [-1,1]
            -> bicubic resize to [1,3,420,840]
            -> clamp, denormalize to [0,255] uint8
            -> permute to (840, 420, 3) for pygame (W, H, C)
        
        Returns:
            numpy array (840, 420, 3) uint8
        """
        x_recon = self.vqvae_decoder(z)  # [1, 3, 256, 512]
        x_recon = F.interpolate(
            x_recon, size=(420, 840),
            mode='bicubic', align_corners=False
        )
        x_recon = x_recon.clamp(-1, 1)
        x_uint8 = ((x_recon + 1.0) * 127.5).byte()  # [1, 3, 420, 840]
        return x_uint8[0].permute(2, 1, 0).cpu().numpy()  # (840, 420, 3)
    
    def _reseed(self, index=None):
        """Reset context buffer to a new seed (random or specified)."""
        idx = index if index is not None else random.randint(0, self.num_seeds - 1)
        self.context_buffer = self.seeds[idx:idx + 1].clone()
        self.seed_index = idx
        self.frame_count = 0
        print(f"Reseeded with seed {idx}")
    
    def _draw_overlay(self):
        """Draw FPS counter and controls hint. This is the ONLY non-AI rendering."""
        fps = self.clock.get_fps()
        fps_text = self.font.render(
            f"FPS: {fps:.0f}  |  Frame: {self.frame_count}", 
            True, (0, 0, 0)
        )
        self.screen.blit(fps_text, (10, 10))
        
        controls = self.font.render(
            "SPACE: Jump  |  R: Restart  |  ESC: Quit", 
            True, (0, 0, 0)
        )
        self.screen.blit(controls, (10, self.display_size[1] - 30))
        
        # Mode indicator
        mode = self.font.render("AI WORLD MODEL", True, (200, 50, 50))
        self.screen.blit(mode, (self.display_size[0] - 180, 10))
    
    def run(self):
        """Main game loop."""
        print(f"\n{'='*60}")
        print("Starting AI-driven game...")
        print(f"ODE steps: {self.ode_steps}, Solver: {self.solver}")
        print(f"Controls: SPACE=Jump, R=Restart, ESC=Quit")
        print(f"{'='*60}\n")
        
        while self.running:
            # ---- 1. Input Collection ----
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    self.running = False
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_ESCAPE:
                        self.running = False
                    elif event.key == pygame.K_r:
                        self._reseed()
            
            # Continuous key state (not event-based) for responsive jumping
            keys = pygame.key.get_pressed()
            action = 1 if keys[pygame.K_SPACE] else 0
            
            # ---- 2. Dynamics Model: predict next latent ----
            z_next, _ = self._predict_next(action)  # [1, 16, 32, 32], [1, 32, 32]
            
            # ---- 3. VQ-VAE Decode: latent -> pixels ----
            pixels = self._decode_to_pixels(z_next)  # numpy (840, 420, 3) uint8
            
            # ---- 4. Display ----
            pygame.surfarray.blit_array(self.screen, pixels)
            self._draw_overlay()
            pygame.display.flip()
            
            # ---- 5. Update context buffer ----
            self.context_buffer = torch.cat(
                [self.context_buffer[:, 1:], z_next.unsqueeze(1)], dim=1
            )
            
            self.frame_count += 1
            self.clock.tick(60)  # cap at 60fps
        
        pygame.quit()
        print(f"\nGenerated {self.frame_count} frames")


def main():
    parser = argparse.ArgumentParser(description="Play AI-driven world model game")
    
    parser.add_argument("--vqvae_checkpoint", type=str, default="checkpoints/vqvae_best.pt",
                        help="Path to VQ-VAE checkpoint")
    parser.add_argument("--dynamics_checkpoint", type=str, default="checkpoints/dynamics_best.pt",
                        help="Path to dynamics model checkpoint")
    parser.add_argument("--seeds_path", type=str, default="latents/seeds.pt",
                        help="Path to seeds.pt")
    parser.add_argument("--ode_steps", type=int, default=10,
                        help="ODE integration steps (more = better quality, slower)")
    parser.add_argument("--solver", type=str, default="euler", choices=["euler", "midpoint"],
                        help="ODE solver (midpoint is 2x slower but more accurate)")
    parser.add_argument("--temperature", type=float, default=1.0,
                        help="Sampling temperature for dynamics logits (>0 stochastic, <=0 argmax)")
    parser.add_argument("--top_k", type=int, default=None,
                        help="Top-k token sampling for dynamics logits (None or <=0 disables)")
    parser.add_argument("--seed_index", type=int, default=None,
                        help="Specific seed index (default: random)")
    parser.add_argument("--width", type=int, default=840,
                        help="Display width")
    parser.add_argument("--height", type=int, default=420,
                        help="Display height")
    parser.add_argument("--no_compile", action="store_true",
                        help="Disable torch.compile")
    
    args = parser.parse_args()
    
    # Check that required files exist
    for path in [args.vqvae_checkpoint, args.dynamics_checkpoint, args.seeds_path]:
        if not os.path.exists(path):
            print(f"Error: Required file not found: {path}")
            print("\nMake sure you have:")
            print("  1. Trained VQ-VAE (python -m vqvae.train)")
            print("  2. Precomputed latents (python precompute_latents.py)")
            print("  3. Trained dynamics model (python -m dynamics.train)")
            return
    
    game = WorldModelGame(
        vqvae_checkpoint=args.vqvae_checkpoint,
        dynamics_checkpoint=args.dynamics_checkpoint,
        seeds_path=args.seeds_path,
        ode_steps=args.ode_steps,
        seed_index=args.seed_index,
        display_size=(args.width, args.height),
        solver=args.solver,
        temperature=args.temperature,
        top_k=args.top_k,
        compile_models=not args.no_compile,
    )
    
    game.run()


if __name__ == "__main__":
    main()
